### ISSUE TITLE
Plugin seems to be dead

### ISSUE THREAD

**Issue by ClusterWood** [ludovicchabant/obsidian-remember-file-state#28]
too bad, but the project really seems to be dead.

**Comment by kassirh** [comment]
Agreed. It was a great plugin, and I am grateful to the original creator. I *think* I've managed to fix a specific problem I was experienced, but I haven't exhaustively tested it and nor do I know if it will fix other problems people are experiencing. 

I was going to create a pull request to incorporate the change I made, but I noticed there's been another pull request open since the 10 March 2024 that was never merged.

If anyone is interested, I was getting this error in dev console:

```sh
app.js:1 RangeError: Selection points outside of document
    at de (app.js:1:276945)
    at new e (app.js:1:285128)
    at e.create (app.js:1:285288)
    at Xe (app.js:1:287668)
    at e.update (app.js:1:289926)
    at RememberFileStatePlugin.restoreState (plugin:obsidian-remember-file-state:261:46)
    at eval (plugin:obsidian-remember-file-state:150:16)
    at Array.forEach (<anonymous>)
    at RememberFileStatePlugin.onLayoutReady (plugin:obsidian-remember-file-state:139:54)
    at eval (plugin:obsidian-remember-file-state:357:14)
(anonymous) @ app.js:1
```

I suspect the cause was me. I was editing Obsidian files in another editor causing the plugin saved selections to become stale. The fix I applied to `main.js` (git diff):

```js
--- main.js
+++ main.js
@@
     this.getState = function(view) {
       const scrollInfo = { top: view.currentMode.getScroll(), left: 0 };
       const cm6editor = view.editor;
       const stateSelection = cm6editor.cm.state.selection;
       const stateSelectionJSON = stateSelection.toJSON();
       const stateData = { "scrollInfo": scrollInfo, "selection": stateSelectionJSON };
       return stateData;
     };
+    this.sanitizeSelection = function(selection, docLength) {
+      if (!selection || typeof selection !== "object") {
+        return null;
+      }
+      var ranges = Array.isArray(selection.ranges) ? selection.ranges : [];
+      if (ranges.length === 0) {
+        return { ranges: [{ anchor: 0, head: 0 }], main: 0 };
+      }
+      var clampedRanges = ranges.map((range) => {
+        var anchor = typeof range.anchor === "number" && !isNaN(range.anchor) ? range.anchor : 0;
+        var head = typeof range.head === "number" && !isNaN(range.head) ? range.head : 0;
+        if (anchor < 0)
+          anchor = 0;
+        if (head < 0)
+          head = 0;
+        if (anchor > docLength)
+          anchor = docLength;
+        if (head > docLength)
+          head = docLength;
+        return { anchor, head };
+      });
+      var main = selection.main;
+      if (typeof main !== "number" || isNaN(main) || main < 0 || main >= clampedRanges.length) {
+        main = 0;
+      }
+      return { ranges: clampedRanges, main };
+    };
     this.restoreState = function(stateData, view) {
       view.currentMode.applyScroll(stateData.scrollInfo.top);
       if (stateData.selection !== void 0) {
         const cm6editor = view.editor;
-        var transaction = cm6editor.cm.state.update({
-          selection: import_state.EditorSelection.fromJSON(stateData.selection)
-        });
-        cm6editor.cm.dispatch(transaction);
+        const docLength = cm6editor.cm.state.doc.length;
+        const sanitizedSelection = this.sanitizeSelection(stateData.selection, docLength);
+        if (!sanitizedSelection) {
+          return;
+        }
+        try {
+          var transaction = cm6editor.cm.state.update({
+            selection: import_state.EditorSelection.fromJSON(sanitizedSelection)
+          });
+          cm6editor.cm.dispatch(transaction);
+        } catch (err) {
+          console.debug("RememberFileState: invalid selection, skipping restore", err);
+        }
       }
     };
```

(ps: Thank you Codex!)
